eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:9993/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: utilisateur
          uri: lb://User
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*), /${path}
        - id: projet
          uri: lb://Projet
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*), /${path}
