eureka:
  client:
    serviceurl:
      defaultZone:http://localhost:9993/Eureka
spring:
  cloud:
      gateway:
          routes:
            -id: microservice-user
            uri: lb://User
            predicates:
              -Path= /utilisateur/**
            filters:
              -RewriterPath=/utilisateur/(?<path>.*), /$\{path}

            -id: microservice-projet
            uri: lb://Projet
            predicates:
              -Path= /projet/**
            filters:
              -RewriterPath=/projet/(?<path>.*), /$\{path}
